development:
  adapter: postgresql
  encoding: unicode
  database: foodunites_us_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: foodunites_us_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: foodunites_us_production
  pool: 5